version: '3.5'

services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6.10
    volumes:
      - /docker_files/mosquitto:/mosquitto
    ports:
      - '1883:1883'
      - '9001:9001'   
    restart: unless-stopped
  mongodb:
    image : mongo:4.4.14
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker_files/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped  

